import Head from 'next/head'
import { Inter } from '@next/font/google'
import HomePage from '../components/Home/HomePage'
import Flashcards from '../components/Flashcards/Flashcards';
import Payment from './Payment/[payment]';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {

  return (
    <>
      <Head>
        <title>Hello Talk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <HomePage />
      <Flashcards /> */}
      <Payment></Payment>
    </>
  );
}
