import Head from 'next/head';
import { Inter } from '@next/font/google';
import HomePage from '../components/Home/HomePage';
import Flashcards from '../components/Flashcards/Flashcards';
import Community from '../components/CommunityPage/Community';
import Cert from '../components/Learn/Cert';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>HelloTalk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </>
  );
}
