import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Package from '../components/packages/Package'
import HomePage from '../components/Home/HomePage'
import Blog from '../components/Blog/Blog'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      {/* Ei comment keu erase korben na apatoto
      
      ei index.js hocche amader home page. eta te apnara ja e add korben shob e homepage e dekha jabe
      
      */}
      <Head>
        <title>Hello Talk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage></HomePage>
      <Package />
    </>
  )
}
